### PR TITLE
Multi-target the library to NET4.0, NET4.6.1 and NETStandard2.0

### LINKED ISSUE #7: .NET Core support
First of all: thanks for sharing this library and also your zwave-lib-dotnet.

I came across it while searching for a library that would allow me to talk to a z-wave stick from a Rasperry Pi running Linux. As far as I can see, the main problem with using your zwave-lib-dotnet is that it depends on your serialport-lib-dotnet which depends on Microsoft Serial.IO.Ports. 
Unfortunately MS currently does not seem to have much interest in a Linux implementation of Serial.IO.Ports for .NET Core although independent contributors already implemented support for Windows on ARM devices.

On the other side there is a quite active project here https://github.com/jcurl/SerialPortStream which now seems to be .NET Core compatible and would open a door to serial ports in the Linux world.
I am not sure whether you are interested in continuing your projects in that direction?
I doubt that I have enough skills and time to do it myself but I am sure I could help with testing.

### PR DESCRIPTION
**Pull request by Bounz**
This should fix #7 and allow anybody to use the library in .Net Core and ASP.Net Core applications.
Also included .Net Core test application.

### CODE REVIEW

**Comment by Bounz** [comment]
@genemars, could you, please, publish the new version of nuget package?

**Comment by genemars** [comment]
@Bounz published! =)

**Comment by gitjsdr26** [comment]
Hi @genemars , 
Are you the repository administrator ?
If so do you manage issues posted ?
Best Regards

**Comment by genemars** [comment]
yes I do.



Il gio 2 apr 2020, 11:59 gitjsdr26 <notifications@github.com> ha scritto:

**Comment by gitjsdr26** [comment]
Thank you.
I posted the issue #18 . Did you see it ?
Regards.

**Comment by genemars** [comment]
Hi @Bounz  what IDE did you use for this?
I am not able to load the project in Rider anymore.
It complains about missing frameworks or msbuild version. What am I supposed to install?

**Comment by gitjsdr26** [comment]
@genemars , IDE is Visual Studio, lastest version 2019 is best.

**Comment by genemars** [comment]
I am using Ubuntu.

**Comment by gitjsdr26** [comment]
@genemars , Framework .Net 4.0 targets only Windows, not Linux. Use instead Mono for Linux.

**Comment by genemars** [comment]
@gitjsdr26 off course I am using mono, but the solution still won't work in Linux.
I would like this to work in Linux too.
@Bounz where are you? =)

**Comment by gitjsdr26** [comment]
@genemars , you can't use this solution. What you can do is to create a new library solution with Mono and take and adapt source files.

**Comment by genemars** [comment]
@gitjsdr26 so maybe it's better to revert this pull request because now I can't see the new version of SerialPortLib available as a nuget packages for ZWaveLib (because of different target framework I guess).

**Comment by gitjsdr26** [comment]
@genemars , I think so, because Bounz is not very active and we cannot merge pull request ourselves.

**Comment by genemars** [comment]
@gitjsdr26, the mantainer of this project it's me.

**Comment by gitjsdr26** [comment]
@genemars , sorry, but I posted some post on another issue, published a pull request and you didn't replied.

**Comment by genemars** [comment]
I was busy and now I could merge your pr, but first I would like to solve this issue with framework targeting,

**Comment by gitjsdr26** [comment]
@genemars , you are welcome.

**Comment by Bounz** [comment]
> Hi @Bounz what IDE did you use for this?
> I am not able to load the project in Rider anymore.
> It complains about missing frameworks or msbuild version. What am I supposed to install?

Hi, @genemars.
I used Rider on MacOS.
Could you show what happens when you load project? What errors do you see?

**Comment by Bounz** [comment]
> @gitjsdr26 so maybe it's better to revert this pull request because now I can't see the new version of SerialPortLib available as a nuget packages for ZWaveLib (because of different target framework I guess).

Tried to reproduce your problem but didn't succeed, everything works 🤷.
What did I do:

- checked out fresh copy of your zwave-lib repository, opened it in Rider 2019.1
- opened NuGet tool window
- NuGet shows SerialPortLib 1.0.19 as available package upgrade
Screenshot 2020-06-13 at 21 38 16
- successfully upgraded SerialPortLib
Screenshot 2020-06-13 at 21 38 43
- successfully rebuilt solution
Screenshot 2020-06-13 at 21 39 12

**Comment by genemars** [comment]
> > Hi @Bounz what IDE did you use for this?
> > I am not able to load the project in Rider anymore.
> > It complains about missing frameworks or msbuild version. What am I supposed to install?
> 
> Hi, @genemars.
> I used Rider on MacOS.
> Could you show what happens when you load project? What errors do you see?
> 
> In Rider you can select target framework from menu in the status bar on the bottom
> image

This is what I see and if I try refreshing packages I can see for a second version 1.0.19 but then it goes back to 1.0.8.

Schermata da 2020-06-13 21-09-39

**Comment by genemars** [comment]
I don't see the .NET framework selection. What I am missing?

Schermata da 2020-06-13 21-15-47

Schermata da 2020-06-13 21-16-08

**Comment by genemars** [comment]
@Bounz I think I got it... I will try installing latest mono from official repository. I am currently using the one from ubuntu repo.

**Comment by genemars** [comment]
@Bounz, that was it. It works now.

**Comment by genemars** [comment]
though I am still not able to see `SerialPortLib` version  `1.0.19` in nuget. =/

**Comment by genemars** [comment]
I finally managed to solve this issue with new SerialPortLib version not showing in nuget by deleting nuget cache:
```
rm -rf .nuget/packages/serialportlib
rm -rf .local/share/NuGet/*
```

**Pull request merged**
